/** Auto-generated by scripts/generate-content.mjs — do not edit by hand. */

export const GENERATED_SPECIES = {
  "charmander": {
    "id": "charmander",
    "name": "小火龙",
    "type": "fire",
    "base": {
      "hp": 42,
      "atk": 55,
      "def": 40,
      "spd": 55
    },
    "move": {
      "name": "火花",
      "power": 35,
      "type": "fire"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/charmander.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "charmeleon",
    "evolveLevel": 8
  },
  "charmeleon": {
    "id": "charmeleon",
    "name": "火恐龙",
    "type": "fire",
    "base": {
      "hp": 51,
      "atk": 67,
      "def": 48,
      "spd": 67
    },
    "move": {
      "name": "火焰牙",
      "power": 53,
      "type": "fire"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/charmeleon.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "charizard",
    "evolveLevel": 16
  },
  "charizard": {
    "id": "charizard",
    "name": "喷火龙",
    "type": "fire",
    "base": {
      "hp": 60,
      "atk": 79,
      "def": 57,
      "spd": 79
    },
    "move": {
      "name": "喷射火焰",
      "power": 71,
      "type": "fire"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/charizard.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_charizard",
    "evolveLevel": 24
  },
  "mega_charizard": {
    "id": "mega_charizard",
    "name": "超级喷火龙",
    "type": "fire",
    "base": {
      "hp": 69,
      "atk": 91,
      "def": 66,
      "spd": 91
    },
    "move": {
      "name": "爆炸烈焰",
      "power": 89,
      "type": "fire"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_charizard.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "weedle": {
    "id": "weedle",
    "name": "独角虫",
    "type": "bug",
    "base": {
      "hp": 38,
      "atk": 50,
      "def": 30,
      "spd": 50
    },
    "move": {
      "name": "虫咬",
      "power": 35,
      "type": "bug"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/weedle.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "kakuna",
    "evolveLevel": 8
  },
  "kakuna": {
    "id": "kakuna",
    "name": "铁壳蛹",
    "type": "bug",
    "base": {
      "hp": 46,
      "atk": 61,
      "def": 36,
      "spd": 61
    },
    "move": {
      "name": "毒针",
      "power": 53,
      "type": "bug"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/kakuna.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "beedrill",
    "evolveLevel": 16
  },
  "beedrill": {
    "id": "beedrill",
    "name": "大针蜂",
    "type": "bug",
    "base": {
      "hp": 54,
      "atk": 72,
      "def": 43,
      "spd": 72
    },
    "move": {
      "name": "双针",
      "power": 71,
      "type": "bug"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/beedrill.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_beedrill",
    "evolveLevel": 24
  },
  "mega_beedrill": {
    "id": "mega_beedrill",
    "name": "超级大针蜂",
    "type": "bug",
    "base": {
      "hp": 63,
      "atk": 83,
      "def": 49,
      "spd": 83
    },
    "move": {
      "name": "飞弹针",
      "power": 89,
      "type": "bug"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_beedrill.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "oddish": {
    "id": "oddish",
    "name": "走路草",
    "type": "grass",
    "base": {
      "hp": 45,
      "atk": 48,
      "def": 50,
      "spd": 35
    },
    "move": {
      "name": "吸取",
      "power": 35,
      "type": "grass"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/oddish.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "gloom",
    "evolveLevel": 8
  },
  "gloom": {
    "id": "gloom",
    "name": "臭臭花",
    "type": "grass",
    "base": {
      "hp": 54,
      "atk": 58,
      "def": 61,
      "spd": 42
    },
    "move": {
      "name": "麻痹粉",
      "power": 53,
      "type": "grass"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/gloom.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "vileplume",
    "evolveLevel": 16
  },
  "vileplume": {
    "id": "vileplume",
    "name": "霸王花",
    "type": "grass",
    "base": {
      "hp": 64,
      "atk": 69,
      "def": 72,
      "spd": 50
    },
    "move": {
      "name": "花瓣舞",
      "power": 71,
      "type": "grass"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/vileplume.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_vileplume",
    "evolveLevel": 24
  },
  "mega_vileplume": {
    "id": "mega_vileplume",
    "name": "超级霸王花",
    "type": "grass",
    "base": {
      "hp": 74,
      "atk": 79,
      "def": 83,
      "spd": 58
    },
    "move": {
      "name": "强力鞭",
      "power": 89,
      "type": "grass"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_vileplume.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "psyduck": {
    "id": "psyduck",
    "name": "可达鸭",
    "type": "psychic",
    "base": {
      "hp": 44,
      "atk": 48,
      "def": 42,
      "spd": 50
    },
    "move": {
      "name": "念力",
      "power": 35,
      "type": "psychic"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/psyduck.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "golduck",
    "evolveLevel": 8
  },
  "golduck": {
    "id": "golduck",
    "name": "哥达鸭",
    "type": "psychic",
    "base": {
      "hp": 53,
      "atk": 58,
      "def": 51,
      "spd": 61
    },
    "move": {
      "name": "水之波动",
      "power": 53,
      "type": "psychic"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/golduck.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "golduck_x",
    "evolveLevel": 16
  },
  "golduck_x": {
    "id": "golduck_x",
    "name": "哥达鸭·念",
    "type": "psychic",
    "base": {
      "hp": 63,
      "atk": 69,
      "def": 60,
      "spd": 72
    },
    "move": {
      "name": "精神强念",
      "power": 71,
      "type": "psychic"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/golduck_x.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_golduck",
    "evolveLevel": 24
  },
  "mega_golduck": {
    "id": "mega_golduck",
    "name": "超级哥达鸭",
    "type": "psychic",
    "base": {
      "hp": 73,
      "atk": 79,
      "def": 69,
      "spd": 83
    },
    "move": {
      "name": "幻象光线",
      "power": 89,
      "type": "psychic"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_golduck.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "machop": {
    "id": "machop",
    "name": "腕力",
    "type": "fighting",
    "base": {
      "hp": 50,
      "atk": 65,
      "def": 40,
      "spd": 35
    },
    "move": {
      "name": "空手劈",
      "power": 35,
      "type": "fighting"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/machop.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "machoke",
    "evolveLevel": 8
  },
  "machoke": {
    "id": "machoke",
    "name": "豪力",
    "type": "fighting",
    "base": {
      "hp": 61,
      "atk": 79,
      "def": 48,
      "spd": 42
    },
    "move": {
      "name": "报复",
      "power": 53,
      "type": "fighting"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/machoke.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "machamp",
    "evolveLevel": 16
  },
  "machamp": {
    "id": "machamp",
    "name": "怪力",
    "type": "fighting",
    "base": {
      "hp": 72,
      "atk": 93,
      "def": 57,
      "spd": 50
    },
    "move": {
      "name": "十字劈",
      "power": 71,
      "type": "fighting"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/machamp.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_machamp",
    "evolveLevel": 24
  },
  "mega_machamp": {
    "id": "mega_machamp",
    "name": "超级怪力",
    "type": "fighting",
    "base": {
      "hp": 83,
      "atk": 107,
      "def": 66,
      "spd": 58
    },
    "move": {
      "name": "近身战",
      "power": 89,
      "type": "fighting"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_machamp.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "magnemite": {
    "id": "magnemite",
    "name": "小磁怪",
    "type": "steel",
    "base": {
      "hp": 35,
      "atk": 50,
      "def": 60,
      "spd": 40
    },
    "move": {
      "name": "电击",
      "power": 35,
      "type": "steel"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/magnemite.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "magneton",
    "evolveLevel": 8
  },
  "magneton": {
    "id": "magneton",
    "name": "三合一磁怪",
    "type": "steel",
    "base": {
      "hp": 42,
      "atk": 61,
      "def": 73,
      "spd": 48
    },
    "move": {
      "name": "电磁飘浮",
      "power": 53,
      "type": "steel"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/magneton.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "magnezone",
    "evolveLevel": 16
  },
  "magnezone": {
    "id": "magnezone",
    "name": "自爆磁怪",
    "type": "steel",
    "base": {
      "hp": 50,
      "atk": 72,
      "def": 86,
      "spd": 57
    },
    "move": {
      "name": "加农光炮",
      "power": 71,
      "type": "steel"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/magnezone.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_magnezone",
    "evolveLevel": 24
  },
  "mega_magnezone": {
    "id": "mega_magnezone",
    "name": "超级自爆磁怪",
    "type": "steel",
    "base": {
      "hp": 58,
      "atk": 83,
      "def": 99,
      "spd": 66
    },
    "move": {
      "name": "铁卷尾",
      "power": 89,
      "type": "steel"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_magnezone.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "vulpix": {
    "id": "vulpix",
    "name": "六尾",
    "type": "fire",
    "base": {
      "hp": 40,
      "atk": 45,
      "def": 40,
      "spd": 58
    },
    "move": {
      "name": "火花",
      "power": 35,
      "type": "fire"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/vulpix.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "ninetales",
    "evolveLevel": 8
  },
  "ninetales": {
    "id": "ninetales",
    "name": "九尾",
    "type": "fire",
    "base": {
      "hp": 48,
      "atk": 54,
      "def": 48,
      "spd": 70
    },
    "move": {
      "name": "奇异之光",
      "power": 53,
      "type": "fire"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/ninetales.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "ninetales_x",
    "evolveLevel": 16
  },
  "ninetales_x": {
    "id": "ninetales_x",
    "name": "九尾·曜",
    "type": "fire",
    "base": {
      "hp": 57,
      "atk": 64,
      "def": 57,
      "spd": 83
    },
    "move": {
      "name": "大字爆炎",
      "power": 71,
      "type": "fire"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/ninetales_x.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_ninetales",
    "evolveLevel": 24
  },
  "mega_ninetales": {
    "id": "mega_ninetales",
    "name": "超级九尾",
    "type": "fire",
    "base": {
      "hp": 66,
      "atk": 74,
      "def": 66,
      "spd": 96
    },
    "move": {
      "name": "炼狱",
      "power": 89,
      "type": "fire"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_ninetales.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "abra": {
    "id": "abra",
    "name": "凯西",
    "type": "psychic",
    "base": {
      "hp": 30,
      "atk": 30,
      "def": 25,
      "spd": 80
    },
    "move": {
      "name": "念力",
      "power": 35,
      "type": "psychic"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/abra.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "kadabra",
    "evolveLevel": 8
  },
  "kadabra": {
    "id": "kadabra",
    "name": "勇基拉",
    "type": "psychic",
    "base": {
      "hp": 36,
      "atk": 36,
      "def": 30,
      "spd": 97
    },
    "move": {
      "name": "幻象光线",
      "power": 53,
      "type": "psychic"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/kadabra.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "alakazam",
    "evolveLevel": 16
  },
  "alakazam": {
    "id": "alakazam",
    "name": "胡地",
    "type": "psychic",
    "base": {
      "hp": 43,
      "atk": 43,
      "def": 36,
      "spd": 115
    },
    "move": {
      "name": "精神强念",
      "power": 71,
      "type": "psychic"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/alakazam.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_alakazam",
    "evolveLevel": 24
  },
  "mega_alakazam": {
    "id": "mega_alakazam",
    "name": "超级胡地",
    "type": "psychic",
    "base": {
      "hp": 49,
      "atk": 49,
      "def": 41,
      "spd": 132
    },
    "move": {
      "name": "未来预知",
      "power": 89,
      "type": "psychic"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_alakazam.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "gastly": {
    "id": "gastly",
    "name": "鬼斯",
    "type": "ghost",
    "base": {
      "hp": 35,
      "atk": 45,
      "def": 30,
      "spd": 70
    },
    "move": {
      "name": "舌舔",
      "power": 35,
      "type": "ghost"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/gastly.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "haunter",
    "evolveLevel": 8
  },
  "haunter": {
    "id": "haunter",
    "name": "鬼斯通",
    "type": "ghost",
    "base": {
      "hp": 42,
      "atk": 54,
      "def": 36,
      "spd": 85
    },
    "move": {
      "name": "影子球",
      "power": 53,
      "type": "ghost"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/haunter.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "gengar",
    "evolveLevel": 16
  },
  "gengar": {
    "id": "gengar",
    "name": "耿鬼",
    "type": "ghost",
    "base": {
      "hp": 50,
      "atk": 64,
      "def": 43,
      "spd": 100
    },
    "move": {
      "name": "恶之波动",
      "power": 71,
      "type": "ghost"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/gengar.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_gengar",
    "evolveLevel": 24
  },
  "mega_gengar": {
    "id": "mega_gengar",
    "name": "超级耿鬼",
    "type": "ghost",
    "base": {
      "hp": 58,
      "atk": 74,
      "def": 49,
      "spd": 116
    },
    "move": {
      "name": "暗影潜袭",
      "power": 89,
      "type": "ghost"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_gengar.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "onix": {
    "id": "onix",
    "name": "大岩蛇",
    "type": "steel",
    "base": {
      "hp": 45,
      "atk": 50,
      "def": 90,
      "spd": 30
    },
    "move": {
      "name": "落石",
      "power": 35,
      "type": "steel"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/onix.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "steelix",
    "evolveLevel": 8
  },
  "steelix": {
    "id": "steelix",
    "name": "大钢蛇",
    "type": "steel",
    "base": {
      "hp": 54,
      "atk": 61,
      "def": 109,
      "spd": 36
    },
    "move": {
      "name": "铁尾",
      "power": 53,
      "type": "steel"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/steelix.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "steelix_x",
    "evolveLevel": 16
  },
  "steelix_x": {
    "id": "steelix_x",
    "name": "大钢蛇·铠",
    "type": "steel",
    "base": {
      "hp": 64,
      "atk": 72,
      "def": 129,
      "spd": 43
    },
    "move": {
      "name": "铁头",
      "power": 71,
      "type": "steel"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/steelix_x.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_steelix",
    "evolveLevel": 24
  },
  "mega_steelix": {
    "id": "mega_steelix",
    "name": "超级大钢蛇",
    "type": "steel",
    "base": {
      "hp": 74,
      "atk": 83,
      "def": 149,
      "spd": 49
    },
    "move": {
      "name": "重磅冲撞",
      "power": 89,
      "type": "steel"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_steelix.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "horsea": {
    "id": "horsea",
    "name": "墨海马",
    "type": "water",
    "base": {
      "hp": 35,
      "atk": 45,
      "def": 45,
      "spd": 55
    },
    "move": {
      "name": "水枪",
      "power": 35,
      "type": "water"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/horsea.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "seadra",
    "evolveLevel": 8
  },
  "seadra": {
    "id": "seadra",
    "name": "海刺龙",
    "type": "water",
    "base": {
      "hp": 42,
      "atk": 54,
      "def": 54,
      "spd": 67
    },
    "move": {
      "name": "龙之怒",
      "power": 53,
      "type": "water"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/seadra.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "kingdra",
    "evolveLevel": 16
  },
  "kingdra": {
    "id": "kingdra",
    "name": "刺龙王",
    "type": "water",
    "base": {
      "hp": 50,
      "atk": 64,
      "def": 64,
      "spd": 79
    },
    "move": {
      "name": "冲浪",
      "power": 71,
      "type": "water"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/kingdra.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_kingdra",
    "evolveLevel": 24
  },
  "mega_kingdra": {
    "id": "mega_kingdra",
    "name": "超级刺龙王",
    "type": "water",
    "base": {
      "hp": 58,
      "atk": 74,
      "def": 74,
      "spd": 91
    },
    "move": {
      "name": "水炮",
      "power": 89,
      "type": "water"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_kingdra.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "magikarp": {
    "id": "magikarp",
    "name": "鲤鱼王",
    "type": "water",
    "base": {
      "hp": 30,
      "atk": 20,
      "def": 40,
      "spd": 60
    },
    "move": {
      "name": "跃起",
      "power": 35,
      "type": "water"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/magikarp.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "gyarados",
    "evolveLevel": 8
  },
  "gyarados": {
    "id": "gyarados",
    "name": "暴鲤龙",
    "type": "water",
    "base": {
      "hp": 36,
      "atk": 24,
      "def": 48,
      "spd": 73
    },
    "move": {
      "name": "咬住",
      "power": 53,
      "type": "water"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/gyarados.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "gyarados_x",
    "evolveLevel": 16
  },
  "gyarados_x": {
    "id": "gyarados_x",
    "name": "暴鲤龙·浪",
    "type": "water",
    "base": {
      "hp": 43,
      "atk": 28,
      "def": 57,
      "spd": 86
    },
    "move": {
      "name": "攀瀑",
      "power": 71,
      "type": "water"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/gyarados_x.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_gyarados",
    "evolveLevel": 24
  },
  "mega_gyarados": {
    "id": "mega_gyarados",
    "name": "超级暴鲤龙",
    "type": "water",
    "base": {
      "hp": 49,
      "atk": 33,
      "def": 66,
      "spd": 99
    },
    "move": {
      "name": "破坏光线",
      "power": 89,
      "type": "water"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_gyarados.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "dratini": {
    "id": "dratini",
    "name": "迷你龙",
    "type": "dragon",
    "base": {
      "hp": 42,
      "atk": 55,
      "def": 45,
      "spd": 45
    },
    "move": {
      "name": "缠绕",
      "power": 35,
      "type": "dragon"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/dratini.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "dragonair",
    "evolveLevel": 8
  },
  "dragonair": {
    "id": "dragonair",
    "name": "哈克龙",
    "type": "dragon",
    "base": {
      "hp": 51,
      "atk": 67,
      "def": 54,
      "spd": 54
    },
    "move": {
      "name": "龙之波动",
      "power": 53,
      "type": "dragon"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/dragonair.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "dragonite",
    "evolveLevel": 16
  },
  "dragonite": {
    "id": "dragonite",
    "name": "快龙",
    "type": "dragon",
    "base": {
      "hp": 60,
      "atk": 79,
      "def": 64,
      "spd": 64
    },
    "move": {
      "name": "逆鳞",
      "power": 71,
      "type": "dragon"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/dragonite.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_dragonite",
    "evolveLevel": 24
  },
  "mega_dragonite": {
    "id": "mega_dragonite",
    "name": "超级快龙",
    "type": "dragon",
    "base": {
      "hp": 69,
      "atk": 91,
      "def": 74,
      "spd": 74
    },
    "move": {
      "name": "流星群",
      "power": 89,
      "type": "dragon"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_dragonite.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "chikorita": {
    "id": "chikorita",
    "name": "菊草叶",
    "type": "grass",
    "base": {
      "hp": 48,
      "atk": 45,
      "def": 55,
      "spd": 40
    },
    "move": {
      "name": "藤鞭",
      "power": 35,
      "type": "grass"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/chikorita.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "bayleef",
    "evolveLevel": 8
  },
  "bayleef": {
    "id": "bayleef",
    "name": "月桂叶",
    "type": "grass",
    "base": {
      "hp": 58,
      "atk": 54,
      "def": 67,
      "spd": 48
    },
    "move": {
      "name": "魔法叶",
      "power": 53,
      "type": "grass"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/bayleef.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "meganium",
    "evolveLevel": 16
  },
  "meganium": {
    "id": "meganium",
    "name": "大竺葵",
    "type": "grass",
    "base": {
      "hp": 69,
      "atk": 64,
      "def": 79,
      "spd": 57
    },
    "move": {
      "name": "花瓣舞",
      "power": 71,
      "type": "grass"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/meganium.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_meganium",
    "evolveLevel": 24
  },
  "mega_meganium": {
    "id": "mega_meganium",
    "name": "超级大竺葵",
    "type": "grass",
    "base": {
      "hp": 79,
      "atk": 74,
      "def": 91,
      "spd": 66
    },
    "move": {
      "name": "日光光束",
      "power": 89,
      "type": "grass"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_meganium.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "mudkip": {
    "id": "mudkip",
    "name": "水跃鱼",
    "type": "water",
    "base": {
      "hp": 50,
      "atk": 55,
      "def": 45,
      "spd": 40
    },
    "move": {
      "name": "水枪",
      "power": 35,
      "type": "water"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/mudkip.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "marshtomp",
    "evolveLevel": 8
  },
  "marshtomp": {
    "id": "marshtomp",
    "name": "沼跃鱼",
    "type": "water",
    "base": {
      "hp": 61,
      "atk": 67,
      "def": 54,
      "spd": 48
    },
    "move": {
      "name": "泥巴射击",
      "power": 53,
      "type": "water"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/marshtomp.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "swampert",
    "evolveLevel": 16
  },
  "swampert": {
    "id": "swampert",
    "name": "巨沼怪",
    "type": "water",
    "base": {
      "hp": 72,
      "atk": 79,
      "def": 64,
      "spd": 57
    },
    "move": {
      "name": "地震",
      "power": 71,
      "type": "water"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/swampert.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_swampert",
    "evolveLevel": 24
  },
  "mega_swampert": {
    "id": "mega_swampert",
    "name": "超级巨沼怪",
    "type": "water",
    "base": {
      "hp": 83,
      "atk": 91,
      "def": 74,
      "spd": 66
    },
    "move": {
      "name": "浊流",
      "power": 89,
      "type": "water"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_swampert.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "ralts": {
    "id": "ralts",
    "name": "拉鲁拉丝",
    "type": "fairy",
    "base": {
      "hp": 32,
      "atk": 35,
      "def": 30,
      "spd": 45
    },
    "move": {
      "name": "念力",
      "power": 35,
      "type": "fairy"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/ralts.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "kirlia",
    "evolveLevel": 8
  },
  "kirlia": {
    "id": "kirlia",
    "name": "奇鲁莉安",
    "type": "fairy",
    "base": {
      "hp": 39,
      "atk": 42,
      "def": 36,
      "spd": 54
    },
    "move": {
      "name": "魅惑之声",
      "power": 53,
      "type": "fairy"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/kirlia.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "gardevoir",
    "evolveLevel": 16
  },
  "gardevoir": {
    "id": "gardevoir",
    "name": "沙奈朵",
    "type": "fairy",
    "base": {
      "hp": 46,
      "atk": 50,
      "def": 43,
      "spd": 64
    },
    "move": {
      "name": "月亮之力",
      "power": 71,
      "type": "fairy"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/gardevoir.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_gardevoir",
    "evolveLevel": 24
  },
  "mega_gardevoir": {
    "id": "mega_gardevoir",
    "name": "超级沙奈朵",
    "type": "fairy",
    "base": {
      "hp": 53,
      "atk": 58,
      "def": 49,
      "spd": 74
    },
    "move": {
      "name": "薄雾球",
      "power": 89,
      "type": "fairy"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_gardevoir.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "aron": {
    "id": "aron",
    "name": "可可多拉",
    "type": "steel",
    "base": {
      "hp": 45,
      "atk": 60,
      "def": 80,
      "spd": 30
    },
    "move": {
      "name": "撞击",
      "power": 35,
      "type": "steel"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/aron.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "lairon",
    "evolveLevel": 8
  },
  "lairon": {
    "id": "lairon",
    "name": "可多拉",
    "type": "steel",
    "base": {
      "hp": 54,
      "atk": 73,
      "def": 97,
      "spd": 36
    },
    "move": {
      "name": "铁头",
      "power": 53,
      "type": "steel"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/lairon.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "aggron",
    "evolveLevel": 16
  },
  "aggron": {
    "id": "aggron",
    "name": "波士可多拉",
    "type": "steel",
    "base": {
      "hp": 64,
      "atk": 86,
      "def": 115,
      "spd": 43
    },
    "move": {
      "name": "金属爆炸",
      "power": 71,
      "type": "steel"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/aggron.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_aggron",
    "evolveLevel": 24
  },
  "mega_aggron": {
    "id": "mega_aggron",
    "name": "超级波士可多拉",
    "type": "steel",
    "base": {
      "hp": 74,
      "atk": 99,
      "def": 132,
      "spd": 49
    },
    "move": {
      "name": "重磅冲撞",
      "power": 89,
      "type": "steel"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_aggron.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "bagon": {
    "id": "bagon",
    "name": "宝贝龙",
    "type": "dragon",
    "base": {
      "hp": 45,
      "atk": 65,
      "def": 45,
      "spd": 45
    },
    "move": {
      "name": "咬住",
      "power": 35,
      "type": "dragon"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/bagon.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "shelgon",
    "evolveLevel": 8
  },
  "shelgon": {
    "id": "shelgon",
    "name": "甲壳龙",
    "type": "dragon",
    "base": {
      "hp": 54,
      "atk": 79,
      "def": 54,
      "spd": 54
    },
    "move": {
      "name": "龙爪",
      "power": 53,
      "type": "dragon"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/shelgon.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "salamence",
    "evolveLevel": 16
  },
  "salamence": {
    "id": "salamence",
    "name": "暴飞龙",
    "type": "dragon",
    "base": {
      "hp": 64,
      "atk": 93,
      "def": 64,
      "spd": 64
    },
    "move": {
      "name": "飞翔",
      "power": 71,
      "type": "dragon"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/salamence.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_salamence",
    "evolveLevel": 24
  },
  "mega_salamence": {
    "id": "mega_salamence",
    "name": "超级暴飞龙",
    "type": "dragon",
    "base": {
      "hp": 74,
      "atk": 107,
      "def": 74,
      "spd": 74
    },
    "move": {
      "name": "流星群",
      "power": 89,
      "type": "dragon"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_salamence.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "spheal": {
    "id": "spheal",
    "name": "海豹球",
    "type": "ice",
    "base": {
      "hp": 55,
      "atk": 45,
      "def": 50,
      "spd": 30
    },
    "move": {
      "name": "细雪",
      "power": 35,
      "type": "ice"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/spheal.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "sealeo",
    "evolveLevel": 8
  },
  "sealeo": {
    "id": "sealeo",
    "name": "海魔狮",
    "type": "ice",
    "base": {
      "hp": 67,
      "atk": 54,
      "def": 61,
      "spd": 36
    },
    "move": {
      "name": "冰砾",
      "power": 53,
      "type": "ice"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/sealeo.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "walrein",
    "evolveLevel": 16
  },
  "walrein": {
    "id": "walrein",
    "name": "帝牙海狮",
    "type": "ice",
    "base": {
      "hp": 79,
      "atk": 64,
      "def": 72,
      "spd": 43
    },
    "move": {
      "name": "暴风雪",
      "power": 71,
      "type": "ice"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/walrein.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_walrein",
    "evolveLevel": 24
  },
  "mega_walrein": {
    "id": "mega_walrein",
    "name": "超级帝牙海狮",
    "type": "ice",
    "base": {
      "hp": 91,
      "atk": 74,
      "def": 83,
      "spd": 49
    },
    "move": {
      "name": "绝对零度",
      "power": 89,
      "type": "ice"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_walrein.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "shinx": {
    "id": "shinx",
    "name": "小猫怪",
    "type": "electric",
    "base": {
      "hp": 42,
      "atk": 55,
      "def": 35,
      "spd": 50
    },
    "move": {
      "name": "电击",
      "power": 35,
      "type": "electric"
    },
    "catchRate": 0.45,
    "sprite": "assets/pokemon/shinx.png",
    "eyeOffset": {
      "x": 0,
      "y": -10
    },
    "evolvesTo": "luxio",
    "evolveLevel": 8
  },
  "luxio": {
    "id": "luxio",
    "name": "勒克猫",
    "type": "electric",
    "base": {
      "hp": 51,
      "atk": 67,
      "def": 42,
      "spd": 61
    },
    "move": {
      "name": "电光",
      "power": 53,
      "type": "electric"
    },
    "catchRate": 0.35,
    "sprite": "assets/pokemon/luxio.png",
    "eyeOffset": {
      "x": 0,
      "y": -9
    },
    "evolvesTo": "luxray",
    "evolveLevel": 16
  },
  "luxray": {
    "id": "luxray",
    "name": "伦琴猫",
    "type": "electric",
    "base": {
      "hp": 60,
      "atk": 79,
      "def": 50,
      "spd": 72
    },
    "move": {
      "name": "疯狂伏特",
      "power": 71,
      "type": "electric"
    },
    "catchRate": 0.25,
    "sprite": "assets/pokemon/luxray.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_luxray",
    "evolveLevel": 24
  },
  "mega_luxray": {
    "id": "mega_luxray",
    "name": "超级伦琴猫",
    "type": "electric",
    "base": {
      "hp": 69,
      "atk": 91,
      "def": 58,
      "spd": 83
    },
    "move": {
      "name": "伏特替换",
      "power": 89,
      "type": "electric"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/mega_luxray.png",
    "eyeOffset": {
      "x": 0,
      "y": -7
    },
    "mega": true
  },
  "cinderace": {
    "id": "cinderace",
    "name": "闪焰王牌",
    "type": "fire",
    "base": {
      "hp": 70,
      "atk": 95,
      "def": 65,
      "spd": 100
    },
    "move": {
      "name": "烈焰球",
      "power": 70,
      "type": "fire"
    },
    "catchRate": 0.15,
    "sprite": "assets/pokemon/cinderace.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_cinderace",
    "evolveLevel": 24
  },
  "mega_cinderace": {
    "id": "mega_cinderace",
    "name": "超级闪焰王牌",
    "type": "fire",
    "base": {
      "hp": 85,
      "atk": 120,
      "def": 80,
      "spd": 120
    },
    "move": {
      "name": "火焰球·极",
      "power": 90,
      "type": "fire"
    },
    "catchRate": 0.08,
    "sprite": "assets/pokemon/mega_cinderace.png",
    "eyeOffset": {
      "x": 0,
      "y": -6
    },
    "mega": true
  },
  "venusaur": {
    "id": "venusaur",
    "name": "妙蛙花",
    "type": "grass",
    "base": {
      "hp": 75,
      "atk": 75,
      "def": 75,
      "spd": 60
    },
    "move": {
      "name": "阳光烈焰",
      "power": 70,
      "type": "grass"
    },
    "catchRate": 0.15,
    "sprite": "assets/pokemon/venusaur.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_venusaur",
    "evolveLevel": 24
  },
  "mega_venusaur": {
    "id": "mega_venusaur",
    "name": "超级妙蛙花",
    "type": "grass",
    "base": {
      "hp": 90,
      "atk": 95,
      "def": 100,
      "spd": 70
    },
    "move": {
      "name": "花瓣暴风",
      "power": 90,
      "type": "grass"
    },
    "catchRate": 0.08,
    "sprite": "assets/pokemon/mega_venusaur.png",
    "eyeOffset": {
      "x": 0,
      "y": -6
    },
    "mega": true
  },
  "blastoise": {
    "id": "blastoise",
    "name": "水箭龟",
    "type": "water",
    "base": {
      "hp": 75,
      "atk": 75,
      "def": 90,
      "spd": 60
    },
    "move": {
      "name": "水炮",
      "power": 70,
      "type": "water"
    },
    "catchRate": 0.15,
    "sprite": "assets/pokemon/blastoise.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_blastoise",
    "evolveLevel": 24
  },
  "mega_blastoise": {
    "id": "mega_blastoise",
    "name": "超级水箭龟",
    "type": "water",
    "base": {
      "hp": 90,
      "atk": 95,
      "def": 115,
      "spd": 70
    },
    "move": {
      "name": "加农水炮",
      "power": 90,
      "type": "water"
    },
    "catchRate": 0.08,
    "sprite": "assets/pokemon/mega_blastoise.png",
    "eyeOffset": {
      "x": 0,
      "y": -6
    },
    "mega": true
  },
  "raichu_x": {
    "id": "raichu_x",
    "name": "雷丘·迅",
    "type": "electric",
    "base": {
      "hp": 65,
      "atk": 95,
      "def": 60,
      "spd": 110
    },
    "move": {
      "name": "电光一闪·霆",
      "power": 70,
      "type": "electric"
    },
    "catchRate": 0.15,
    "sprite": "assets/pokemon/raichu_x.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_raichu",
    "evolveLevel": 24
  },
  "mega_raichu": {
    "id": "mega_raichu",
    "name": "超级雷丘",
    "type": "electric",
    "base": {
      "hp": 80,
      "atk": 115,
      "def": 75,
      "spd": 130
    },
    "move": {
      "name": "伏特攻击",
      "power": 90,
      "type": "electric"
    },
    "catchRate": 0.08,
    "sprite": "assets/pokemon/mega_raichu.png",
    "eyeOffset": {
      "x": 0,
      "y": -6
    },
    "mega": true
  },
  "golem": {
    "id": "golem",
    "name": "隆隆岩",
    "type": "rock",
    "base": {
      "hp": 80,
      "atk": 100,
      "def": 115,
      "spd": 40
    },
    "move": {
      "name": "地震",
      "power": 70,
      "type": "rock"
    },
    "catchRate": 0.15,
    "sprite": "assets/pokemon/golem.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    },
    "evolvesTo": "mega_golem",
    "evolveLevel": 24
  },
  "mega_golem": {
    "id": "mega_golem",
    "name": "超级隆隆岩",
    "type": "rock",
    "base": {
      "hp": 95,
      "atk": 125,
      "def": 140,
      "spd": 50
    },
    "move": {
      "name": "岩石崩塌",
      "power": 90,
      "type": "rock"
    },
    "catchRate": 0.08,
    "sprite": "assets/pokemon/mega_golem.png",
    "eyeOffset": {
      "x": 0,
      "y": -6
    },
    "mega": true
  }
};

export const GENERATED_MAPS = {
  "misty_woods": {
    "id": "misty_woods",
    "name": "迷雾森林",
    "image": "assets/maps/misty_woods.png",
    "bossChance": 0.1,
    "encounters": [
      {
        "id": "w-weedle",
        "kind": "wild",
        "speciesId": "weedle",
        "level": 9,
        "x": 30,
        "y": 55
      },
      {
        "id": "w-oddish",
        "kind": "wild",
        "speciesId": "oddish",
        "level": 10,
        "x": 55,
        "y": 60
      },
      {
        "id": "t-ranger",
        "kind": "trainer",
        "trainerName": "巡林员",
        "reward": 450,
        "x": 75,
        "y": 45,
        "team": [
          { "speciesId": "chikorita", "level": 11 },
          { "speciesId": "oddish", "level": 10 },
          { "speciesId": "weedle", "level": 9 },
          { "speciesId": "bulbasaur", "level": 11 }
        ]
      },
      {
        "id": "t-picnic",
        "kind": "trainer",
        "trainerName": "野餐女孩",
        "reward": 400,
        "x": 18,
        "y": 40,
        "team": [
          { "speciesId": "oddish", "level": 9 },
          { "speciesId": "chikorita", "level": 10 },
          { "speciesId": "weedle", "level": 10 }
        ]
      },
      {
        "id": "t-scholar",
        "kind": "trainer",
        "trainerName": "森林学者",
        "reward": 500,
        "x": 48,
        "y": 32,
        "team": [
          { "speciesId": "bulbasaur", "level": 10 },
          { "speciesId": "ivysaur", "level": 11 },
          { "speciesId": "oddish", "level": 11 },
          { "speciesId": "chikorita", "level": 9 },
          { "speciesId": "weedle", "level": 11 }
        ]
      }
    ]
  },
  "thunder_ridge": {
    "id": "thunder_ridge",
    "name": "雷鸣山脊",
    "image": "assets/maps/thunder_ridge.png",
    "bossChance": 0.12,
    "encounters": [
      {
        "id": "w-shinx",
        "kind": "wild",
        "speciesId": "shinx",
        "level": 11,
        "x": 28,
        "y": 52
      },
      {
        "id": "w-magnemite",
        "kind": "wild",
        "speciesId": "magnemite",
        "level": 12,
        "x": 50,
        "y": 48
      },
      {
        "id": "t-engineer",
        "kind": "trainer",
        "trainerName": "电工",
        "reward": 550,
        "x": 72,
        "y": 42,
        "team": [
          { "speciesId": "abra", "level": 13 },
          { "speciesId": "shinx", "level": 12 },
          { "speciesId": "magnemite", "level": 11 },
          { "speciesId": "pikachu", "level": 13 }
        ]
      },
      {
        "id": "t-climber",
        "kind": "trainer",
        "trainerName": "登山者",
        "reward": 500,
        "x": 40,
        "y": 68,
        "team": [
          { "speciesId": "magnemite", "level": 11 },
          { "speciesId": "shinx", "level": 12 },
          { "speciesId": "geodude", "level": 12 }
        ]
      },
      {
        "id": "t-researcher",
        "kind": "trainer",
        "trainerName": "研究员",
        "reward": 600,
        "x": 85,
        "y": 58,
        "team": [
          { "speciesId": "pikachu", "level": 12 },
          { "speciesId": "raichu", "level": 13 },
          { "speciesId": "shinx", "level": 13 },
          { "speciesId": "magnemite", "level": 12 },
          { "speciesId": "abra", "level": 11 },
          { "speciesId": "kadabra", "level": 13 }
        ]
      }
    ]
  },
  "ancient_ruins": {
    "id": "ancient_ruins",
    "name": "古代遗迹",
    "image": "assets/maps/ancient_ruins.png",
    "bossChance": 0.14,
    "encounters": [
      {
        "id": "w-gastly",
        "kind": "wild",
        "speciesId": "gastly",
        "level": 13,
        "x": 32,
        "y": 50
      },
      {
        "id": "w-aron",
        "kind": "wild",
        "speciesId": "aron",
        "level": 14,
        "x": 58,
        "y": 58
      },
      {
        "id": "t-ruins",
        "kind": "trainer",
        "trainerName": "遗迹猎人",
        "reward": 650,
        "x": 78,
        "y": 40,
        "team": [
          { "speciesId": "machop", "level": 15 },
          { "speciesId": "gastly", "level": 14 },
          { "speciesId": "aron", "level": 13 },
          { "speciesId": "onix", "level": 15 }
        ]
      },
      {
        "id": "t-archaeologist",
        "kind": "trainer",
        "trainerName": "考古家",
        "reward": 600,
        "x": 18,
        "y": 68,
        "team": [
          { "speciesId": "gastly", "level": 13 },
          { "speciesId": "aron", "level": 14 },
          { "speciesId": "machop", "level": 14 }
        ]
      },
      {
        "id": "t-apprentice",
        "kind": "trainer",
        "trainerName": "道馆学徒",
        "reward": 700,
        "x": 48,
        "y": 35,
        "team": [
          { "speciesId": "machoke", "level": 15 },
          { "speciesId": "haunter", "level": 15 },
          { "speciesId": "lairon", "level": 14 },
          { "speciesId": "graveler", "level": 15 },
          { "speciesId": "kadabra", "level": 14 }
        ]
      }
    ]
  },
  "frost_lake": {
    "id": "frost_lake",
    "name": "霜冻湖泊",
    "image": "assets/maps/frost_lake.png",
    "bossChance": 0.15,
    "encounters": [
      {
        "id": "w-spheal",
        "kind": "wild",
        "speciesId": "spheal",
        "level": 15,
        "x": 35,
        "y": 58
      },
      {
        "id": "w-horsea",
        "kind": "wild",
        "speciesId": "horsea",
        "level": 16,
        "x": 55,
        "y": 62
      },
      {
        "id": "t-skier",
        "kind": "trainer",
        "trainerName": "滑雪者",
        "reward": 750,
        "x": 74,
        "y": 44,
        "team": [
          { "speciesId": "psyduck", "level": 17 },
          { "speciesId": "spheal", "level": 16 },
          { "speciesId": "horsea", "level": 15 },
          { "speciesId": "sealeo", "level": 17 }
        ]
      },
      {
        "id": "t-icefisher",
        "kind": "trainer",
        "trainerName": "冰上钓手",
        "reward": 700,
        "x": 20,
        "y": 40,
        "team": [
          { "speciesId": "spheal", "level": 15 },
          { "speciesId": "horsea", "level": 16 },
          { "speciesId": "magikarp", "level": 15 }
        ]
      },
      {
        "id": "t-patrol",
        "kind": "trainer",
        "trainerName": "雪地巡逻",
        "reward": 800,
        "x": 48,
        "y": 32,
        "team": [
          { "speciesId": "sealeo", "level": 17 },
          { "speciesId": "golduck", "level": 17 },
          { "speciesId": "seadra", "level": 16 },
          { "speciesId": "spheal", "level": 16 },
          { "speciesId": "wartortle", "level": 17 },
          { "speciesId": "walrein", "level": 17 }
        ]
      }
    ]
  },
  "sky_terrace": {
    "id": "sky_terrace",
    "name": "云端花园",
    "image": "assets/maps/sky_terrace.png",
    "bossChance": 0.16,
    "encounters": [
      {
        "id": "w-ralts",
        "kind": "wild",
        "speciesId": "ralts",
        "level": 17,
        "x": 30,
        "y": 50
      },
      {
        "id": "w-bagon",
        "kind": "wild",
        "speciesId": "bagon",
        "level": 18,
        "x": 52,
        "y": 46
      },
      {
        "id": "t-pilot",
        "kind": "trainer",
        "trainerName": "飞行员",
        "reward": 900,
        "x": 76,
        "y": 40,
        "team": [
          { "speciesId": "vulpix", "level": 20 },
          { "speciesId": "ralts", "level": 18 },
          { "speciesId": "bagon", "level": 17 },
          { "speciesId": "ninetales", "level": 20 }
        ]
      },
      {
        "id": "t-wind",
        "kind": "trainer",
        "trainerName": "风之训练家",
        "reward": 800,
        "x": 18,
        "y": 68,
        "team": [
          { "speciesId": "bagon", "level": 17 },
          { "speciesId": "ralts", "level": 18 },
          { "speciesId": "vulpix", "level": 18 }
        ]
      },
      {
        "id": "t-terrace",
        "kind": "trainer",
        "trainerName": "天台对决",
        "reward": 1000,
        "x": 62,
        "y": 62,
        "team": [
          { "speciesId": "charizard", "level": 20 },
          { "speciesId": "kirlia", "level": 19 },
          { "speciesId": "shelgon", "level": 19 },
          { "speciesId": "ninetales", "level": 20 },
          { "speciesId": "gardevoir", "level": 20 }
        ]
      }
    ]
  },
  "champion_path": {
    "id": "champion_path",
    "name": "冠军之路",
    "image": "assets/maps/champion_path.png",
    "bossChance": 0.2,
    "encounters": [
      {
        "id": "w-dratini",
        "kind": "wild",
        "speciesId": "dratini",
        "level": 20,
        "x": 28,
        "y": 52
      },
      {
        "id": "w-magikarp",
        "kind": "wild",
        "speciesId": "magikarp",
        "level": 21,
        "x": 48,
        "y": 60
      },
      {
        "id": "w-charmander",
        "kind": "wild",
        "speciesId": "charmander",
        "level": 22,
        "x": 62,
        "y": 48
      },
      {
        "id": "t-champ",
        "kind": "trainer",
        "trainerName": "挑战者",
        "reward": 1200,
        "x": 80,
        "y": 38,
        "team": [
          { "speciesId": "onix", "level": 24 },
          { "speciesId": "dratini", "level": 22 },
          { "speciesId": "charizard", "level": 23 },
          { "speciesId": "dragonair", "level": 24 },
          { "speciesId": "steelix", "level": 24 },
          { "speciesId": "gyarados", "level": 23 }
        ]
      },
      {
        "id": "t-elite",
        "kind": "trainer",
        "trainerName": "精英",
        "reward": 1000,
        "x": 18,
        "y": 36,
        "team": [
          { "speciesId": "dragonite", "level": 24 },
          { "speciesId": "alakazam", "level": 23 },
          { "speciesId": "walrein", "level": 22 },
          { "speciesId": "aggron", "level": 24 }
        ]
      },
      {
        "id": "t-finalist",
        "kind": "trainer",
        "trainerName": "候补冠军",
        "reward": 1400,
        "x": 40,
        "y": 38,
        "team": [
          { "speciesId": "salamence", "level": 24 },
          { "speciesId": "swampert", "level": 23 },
          { "speciesId": "blastoise", "level": 22 },
          { "speciesId": "venusaur", "level": 23 },
          { "speciesId": "machamp", "level": 24 },
          { "speciesId": "magnezone", "level": 22 }
        ]
      }
    ]
  }
};
