/** Auto-generated by scripts/generate-region.mjs — do not edit by hand. */

export const REGION_SPECIES = {
  "cyndaquil": {
    "id": "cyndaquil",
    "name": "火球鼠",
    "type": "fire",
    "base": {
      "hp": 62,
      "atk": 72,
      "def": 50,
      "spd": 66
    },
    "move": {
      "name": "火花",
      "power": 45,
      "type": "fire"
    },
    "catchRate": 0.42,
    "sprite": "assets/pokemon/cyndaquil.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "growlithe": {
    "id": "growlithe",
    "name": "卡蒂狗",
    "type": "fire",
    "base": {
      "hp": 62,
      "atk": 72,
      "def": 50,
      "spd": 66
    },
    "move": {
      "name": "咬住",
      "power": 45,
      "type": "fire"
    },
    "catchRate": 0.42,
    "sprite": "assets/pokemon/growlithe.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "slugma": {
    "id": "slugma",
    "name": "熔岩虫",
    "type": "fire",
    "base": {
      "hp": 62,
      "atk": 72,
      "def": 50,
      "spd": 66
    },
    "move": {
      "name": "火花",
      "power": 45,
      "type": "fire"
    },
    "catchRate": 0.42,
    "sprite": "assets/pokemon/slugma.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "numel": {
    "id": "numel",
    "name": "呆火驼",
    "type": "fire",
    "base": {
      "hp": 62,
      "atk": 72,
      "def": 50,
      "spd": 66
    },
    "move": {
      "name": "撞击",
      "power": 45,
      "type": "fire"
    },
    "catchRate": 0.42,
    "sprite": "assets/pokemon/numel.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "torchic": {
    "id": "torchic",
    "name": "火稚鸡",
    "type": "fire",
    "base": {
      "hp": 62,
      "atk": 72,
      "def": 50,
      "spd": 66
    },
    "move": {
      "name": "火花",
      "power": 45,
      "type": "fire"
    },
    "catchRate": 0.42,
    "sprite": "assets/pokemon/torchic.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "totodile": {
    "id": "totodile",
    "name": "小锯鳄",
    "type": "water",
    "base": {
      "hp": 73,
      "atk": 67,
      "def": 71,
      "spd": 60
    },
    "move": {
      "name": "水枪",
      "power": 49,
      "type": "water"
    },
    "catchRate": 0.39,
    "sprite": "assets/pokemon/totodile.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "poliwag": {
    "id": "poliwag",
    "name": "蚊香蝌蚪",
    "type": "water",
    "base": {
      "hp": 73,
      "atk": 67,
      "def": 71,
      "spd": 60
    },
    "move": {
      "name": "泡沫",
      "power": 49,
      "type": "water"
    },
    "catchRate": 0.39,
    "sprite": "assets/pokemon/poliwag.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "staryu": {
    "id": "staryu",
    "name": "海星星",
    "type": "water",
    "base": {
      "hp": 73,
      "atk": 67,
      "def": 71,
      "spd": 60
    },
    "move": {
      "name": "水枪",
      "power": 49,
      "type": "water"
    },
    "catchRate": 0.39,
    "sprite": "assets/pokemon/staryu.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "chinchou": {
    "id": "chinchou",
    "name": "灯笼鱼",
    "type": "water",
    "base": {
      "hp": 73,
      "atk": 67,
      "def": 71,
      "spd": 60
    },
    "move": {
      "name": "电击",
      "power": 49,
      "type": "water"
    },
    "catchRate": 0.39,
    "sprite": "assets/pokemon/chinchou.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "piplup": {
    "id": "piplup",
    "name": "波加曼",
    "type": "water",
    "base": {
      "hp": 73,
      "atk": 67,
      "def": 71,
      "spd": 60
    },
    "move": {
      "name": "水枪",
      "power": 49,
      "type": "water"
    },
    "catchRate": 0.39,
    "sprite": "assets/pokemon/piplup.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "misdreavus": {
    "id": "misdreavus",
    "name": "梦妖",
    "type": "ghost",
    "base": {
      "hp": 62,
      "atk": 89,
      "def": 59,
      "spd": 91
    },
    "move": {
      "name": "影子球",
      "power": 53,
      "type": "ghost"
    },
    "catchRate": 0.36,
    "sprite": "assets/pokemon/misdreavus.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "sableye": {
    "id": "sableye",
    "name": "勾魂眼",
    "type": "dark",
    "base": {
      "hp": 69,
      "atk": 91,
      "def": 62,
      "spd": 86
    },
    "move": {
      "name": "抓",
      "power": 53,
      "type": "dark"
    },
    "catchRate": 0.36,
    "sprite": "assets/pokemon/sableye.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "shuppet": {
    "id": "shuppet",
    "name": "怨影娃娃",
    "type": "ghost",
    "base": {
      "hp": 62,
      "atk": 89,
      "def": 59,
      "spd": 91
    },
    "move": {
      "name": "黑夜魔影",
      "power": 53,
      "type": "ghost"
    },
    "catchRate": 0.36,
    "sprite": "assets/pokemon/shuppet.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "duskull": {
    "id": "duskull",
    "name": "夜巡灵",
    "type": "ghost",
    "base": {
      "hp": 62,
      "atk": 89,
      "def": 59,
      "spd": 91
    },
    "move": {
      "name": "影子球",
      "power": 53,
      "type": "ghost"
    },
    "catchRate": 0.36,
    "sprite": "assets/pokemon/duskull.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "murkrow": {
    "id": "murkrow",
    "name": "黑暗鸦",
    "type": "dark",
    "base": {
      "hp": 69,
      "atk": 91,
      "def": 62,
      "spd": 86
    },
    "move": {
      "name": "啄",
      "power": 53,
      "type": "dark"
    },
    "catchRate": 0.36,
    "sprite": "assets/pokemon/murkrow.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "treecko": {
    "id": "treecko",
    "name": "木守宫",
    "type": "grass",
    "base": {
      "hp": 89,
      "atk": 78,
      "def": 87,
      "spd": 68
    },
    "move": {
      "name": "藤鞭",
      "power": 57,
      "type": "grass"
    },
    "catchRate": 0.32999999999999996,
    "sprite": "assets/pokemon/treecko.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "bellsprout": {
    "id": "bellsprout",
    "name": "喇叭芽",
    "type": "grass",
    "base": {
      "hp": 89,
      "atk": 78,
      "def": 87,
      "spd": 68
    },
    "move": {
      "name": "藤鞭",
      "power": 57,
      "type": "grass"
    },
    "catchRate": 0.32999999999999996,
    "sprite": "assets/pokemon/bellsprout.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "paras": {
    "id": "paras",
    "name": "派拉斯",
    "type": "bug",
    "base": {
      "hp": 78,
      "atk": 97,
      "def": 73,
      "spd": 97
    },
    "move": {
      "name": "吸取",
      "power": 57,
      "type": "bug"
    },
    "catchRate": 0.32999999999999996,
    "sprite": "assets/pokemon/paras.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "scyther": {
    "id": "scyther",
    "name": "飞天螳螂",
    "type": "bug",
    "base": {
      "hp": 78,
      "atk": 97,
      "def": 73,
      "spd": 97
    },
    "move": {
      "name": "连斩",
      "power": 57,
      "type": "bug"
    },
    "catchRate": 0.32999999999999996,
    "sprite": "assets/pokemon/scyther.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "snivy": {
    "id": "snivy",
    "name": "藤藤蛇",
    "type": "grass",
    "base": {
      "hp": 89,
      "atk": 78,
      "def": 87,
      "spd": 68
    },
    "move": {
      "name": "藤鞭",
      "power": 57,
      "type": "grass"
    },
    "catchRate": 0.32999999999999996,
    "sprite": "assets/pokemon/snivy.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "electrike": {
    "id": "electrike",
    "name": "落雷兽",
    "type": "electric",
    "base": {
      "hp": 76,
      "atk": 103,
      "def": 68,
      "spd": 115
    },
    "move": {
      "name": "电击",
      "power": 61,
      "type": "electric"
    },
    "catchRate": 0.3,
    "sprite": "assets/pokemon/electrike.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "mareep": {
    "id": "mareep",
    "name": "咩利羊",
    "type": "electric",
    "base": {
      "hp": 76,
      "atk": 103,
      "def": 68,
      "spd": 115
    },
    "move": {
      "name": "电击",
      "power": 61,
      "type": "electric"
    },
    "catchRate": 0.3,
    "sprite": "assets/pokemon/mareep.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "voltorb": {
    "id": "voltorb",
    "name": "霹雳电球",
    "type": "electric",
    "base": {
      "hp": 76,
      "atk": 103,
      "def": 68,
      "spd": 115
    },
    "move": {
      "name": "电击",
      "power": 61,
      "type": "electric"
    },
    "catchRate": 0.3,
    "sprite": "assets/pokemon/voltorb.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "electabuzz": {
    "id": "electabuzz",
    "name": "电击兽",
    "type": "electric",
    "base": {
      "hp": 76,
      "atk": 103,
      "def": 68,
      "spd": 115
    },
    "move": {
      "name": "雷电拳",
      "power": 61,
      "type": "electric"
    },
    "catchRate": 0.3,
    "sprite": "assets/pokemon/electabuzz.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "plusle": {
    "id": "plusle",
    "name": "正电拍拍",
    "type": "electric",
    "base": {
      "hp": 76,
      "atk": 103,
      "def": 68,
      "spd": 115
    },
    "move": {
      "name": "电光",
      "power": 61,
      "type": "electric"
    },
    "catchRate": 0.3,
    "sprite": "assets/pokemon/plusle.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "swinub": {
    "id": "swinub",
    "name": "小山猪",
    "type": "ice",
    "base": {
      "hp": 108,
      "atk": 99,
      "def": 92,
      "spd": 80
    },
    "move": {
      "name": "细雪",
      "power": 65,
      "type": "ice"
    },
    "catchRate": 0.27,
    "sprite": "assets/pokemon/swinub.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "snover": {
    "id": "snover",
    "name": "雪笠怪",
    "type": "ice",
    "base": {
      "hp": 108,
      "atk": 99,
      "def": 92,
      "spd": 80
    },
    "move": {
      "name": "冰砾",
      "power": 65,
      "type": "ice"
    },
    "catchRate": 0.27,
    "sprite": "assets/pokemon/snover.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "sneasel": {
    "id": "sneasel",
    "name": "狃拉",
    "type": "dark",
    "base": {
      "hp": 89,
      "atk": 118,
      "def": 80,
      "spd": 112
    },
    "move": {
      "name": "抓",
      "power": 65,
      "type": "dark"
    },
    "catchRate": 0.27,
    "sprite": "assets/pokemon/sneasel.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "cubchoo": {
    "id": "cubchoo",
    "name": "喷嚏熊",
    "type": "ice",
    "base": {
      "hp": 108,
      "atk": 99,
      "def": 92,
      "spd": 80
    },
    "move": {
      "name": "细雪",
      "power": 65,
      "type": "ice"
    },
    "catchRate": 0.27,
    "sprite": "assets/pokemon/cubchoo.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "vanillite": {
    "id": "vanillite",
    "name": "迷你冰",
    "type": "ice",
    "base": {
      "hp": 108,
      "atk": 99,
      "def": 92,
      "spd": 80
    },
    "move": {
      "name": "冰冻之风",
      "power": 65,
      "type": "ice"
    },
    "catchRate": 0.27,
    "sprite": "assets/pokemon/vanillite.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "larvitar": {
    "id": "larvitar",
    "name": "幼基拉斯",
    "type": "rock",
    "base": {
      "hp": 127,
      "atk": 130,
      "def": 144,
      "spd": 65
    },
    "move": {
      "name": "落石",
      "power": 69,
      "type": "rock"
    },
    "catchRate": 0.24,
    "sprite": "assets/pokemon/larvitar.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "gible": {
    "id": "gible",
    "name": "圆陆鲨",
    "type": "dragon",
    "base": {
      "hp": 120,
      "atk": 137,
      "def": 103,
      "spd": 110
    },
    "move": {
      "name": "龙息",
      "power": 69,
      "type": "dragon"
    },
    "catchRate": 0.24,
    "sprite": "assets/pokemon/gible.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "axew": {
    "id": "axew",
    "name": "牙牙",
    "type": "dragon",
    "base": {
      "hp": 120,
      "atk": 137,
      "def": 103,
      "spd": 110
    },
    "move": {
      "name": "龙爪",
      "power": 69,
      "type": "dragon"
    },
    "catchRate": 0.24,
    "sprite": "assets/pokemon/axew.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "trapinch": {
    "id": "trapinch",
    "name": "大颚蚁",
    "type": "ground",
    "base": {
      "hp": 123,
      "atk": 134,
      "def": 123,
      "spd": 72
    },
    "move": {
      "name": "咬住",
      "power": 69,
      "type": "ground"
    },
    "catchRate": 0.24,
    "sprite": "assets/pokemon/trapinch.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "rhyhorn": {
    "id": "rhyhorn",
    "name": "独角犀牛",
    "type": "rock",
    "base": {
      "hp": 127,
      "atk": 130,
      "def": 144,
      "spd": 65
    },
    "move": {
      "name": "角撞",
      "power": 69,
      "type": "rock"
    },
    "catchRate": 0.24,
    "sprite": "assets/pokemon/rhyhorn.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "clefairy": {
    "id": "clefairy",
    "name": "皮皮",
    "type": "fairy",
    "base": {
      "hp": 128,
      "atk": 106,
      "def": 117,
      "spd": 99
    },
    "move": {
      "name": "拍击",
      "power": 73,
      "type": "fairy"
    },
    "catchRate": 0.21,
    "sprite": "assets/pokemon/clefairy.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "jigglypuff": {
    "id": "jigglypuff",
    "name": "胖丁",
    "type": "fairy",
    "base": {
      "hp": 128,
      "atk": 106,
      "def": 117,
      "spd": 99
    },
    "move": {
      "name": "唱歌",
      "power": 73,
      "type": "fairy"
    },
    "catchRate": 0.21,
    "sprite": "assets/pokemon/jigglypuff.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "togepi": {
    "id": "togepi",
    "name": "波克比",
    "type": "fairy",
    "base": {
      "hp": 128,
      "atk": 106,
      "def": 117,
      "spd": 99
    },
    "move": {
      "name": "魅惑之声",
      "power": 73,
      "type": "fairy"
    },
    "catchRate": 0.21,
    "sprite": "assets/pokemon/togepi.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "snubbull": {
    "id": "snubbull",
    "name": "布鲁",
    "type": "fairy",
    "base": {
      "hp": 128,
      "atk": 106,
      "def": 117,
      "spd": 99
    },
    "move": {
      "name": "咬住",
      "power": 73,
      "type": "fairy"
    },
    "catchRate": 0.21,
    "sprite": "assets/pokemon/snubbull.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "marill": {
    "id": "marill",
    "name": "玛力露",
    "type": "water",
    "base": {
      "hp": 121,
      "atk": 110,
      "def": 117,
      "spd": 99
    },
    "move": {
      "name": "水枪",
      "power": 73,
      "type": "water"
    },
    "catchRate": 0.21,
    "sprite": "assets/pokemon/marill.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "hitmonlee": {
    "id": "hitmonlee",
    "name": "飞腿郎",
    "type": "fighting",
    "base": {
      "hp": 133,
      "atk": 160,
      "def": 109,
      "spd": 125
    },
    "move": {
      "name": "飞踢",
      "power": 77,
      "type": "fighting"
    },
    "catchRate": 0.18,
    "sprite": "assets/pokemon/hitmonlee.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "hitmonchan": {
    "id": "hitmonchan",
    "name": "快拳郎",
    "type": "fighting",
    "base": {
      "hp": 133,
      "atk": 160,
      "def": 109,
      "spd": 125
    },
    "move": {
      "name": "冲天拳",
      "power": 77,
      "type": "fighting"
    },
    "catchRate": 0.18,
    "sprite": "assets/pokemon/hitmonchan.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "tyrogue": {
    "id": "tyrogue",
    "name": "无畏小子",
    "type": "fighting",
    "base": {
      "hp": 133,
      "atk": 160,
      "def": 109,
      "spd": 125
    },
    "move": {
      "name": "撞击",
      "power": 77,
      "type": "fighting"
    },
    "catchRate": 0.18,
    "sprite": "assets/pokemon/tyrogue.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "makuhita": {
    "id": "makuhita",
    "name": "幕下力士",
    "type": "fighting",
    "base": {
      "hp": 133,
      "atk": 160,
      "def": 109,
      "spd": 125
    },
    "move": {
      "name": "臂锤",
      "power": 77,
      "type": "fighting"
    },
    "catchRate": 0.18,
    "sprite": "assets/pokemon/makuhita.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "riolu": {
    "id": "riolu",
    "name": "利欧路",
    "type": "fighting",
    "base": {
      "hp": 133,
      "atk": 160,
      "def": 109,
      "spd": 125
    },
    "move": {
      "name": "真空波",
      "power": 77,
      "type": "fighting"
    },
    "catchRate": 0.18,
    "sprite": "assets/pokemon/riolu.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "lucario": {
    "id": "lucario",
    "name": "路卡利欧",
    "type": "fighting",
    "base": {
      "hp": 141,
      "atk": 170,
      "def": 116,
      "spd": 133
    },
    "move": {
      "name": "波导弹",
      "power": 81,
      "type": "fighting"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/lucario.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "garchomp": {
    "id": "garchomp",
    "name": "烈咬陆鲨",
    "type": "dragon",
    "base": {
      "hp": 145,
      "atk": 166,
      "def": 124,
      "spd": 133
    },
    "move": {
      "name": "龙爪",
      "power": 81,
      "type": "dragon"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/garchomp.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "metagross": {
    "id": "metagross",
    "name": "巨金怪",
    "type": "steel",
    "base": {
      "hp": 149,
      "atk": 158,
      "def": 191,
      "spd": 91
    },
    "move": {
      "name": "彗星拳",
      "power": 81,
      "type": "steel"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/metagross.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "tyranitar": {
    "id": "tyranitar",
    "name": "班基拉斯",
    "type": "rock",
    "base": {
      "hp": 153,
      "atk": 158,
      "def": 174,
      "spd": 79
    },
    "move": {
      "name": "岩崩",
      "power": 81,
      "type": "rock"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/tyranitar.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  },
  "togekiss": {
    "id": "togekiss",
    "name": "波克基斯",
    "type": "fairy",
    "base": {
      "hp": 145,
      "atk": 120,
      "def": 133,
      "spd": 112
    },
    "move": {
      "name": "空气斩",
      "power": 81,
      "type": "fairy"
    },
    "catchRate": 0.14999999999999997,
    "sprite": "assets/pokemon/togekiss.png",
    "eyeOffset": {
      "x": 0,
      "y": -8
    }
  }
};

export const REGION_MAPS = {
  "lava_canyon": {
    "id": "lava_canyon",
    "name": "熔岩峡谷",
    "image": "assets/maps/lava_canyon.png",
    "bossChance": 0.12,
    "encounters": [
      {
        "id": "lava_canyon-w0",
        "kind": "wild",
        "speciesId": "cyndaquil",
        "level": 26,
        "x": 22,
        "y": 62
      },
      {
        "id": "lava_canyon-w1",
        "kind": "wild",
        "speciesId": "growlithe",
        "level": 27,
        "x": 40,
        "y": 48
      },
      {
        "id": "lava_canyon-w2",
        "kind": "wild",
        "speciesId": "slugma",
        "level": 28,
        "x": 58,
        "y": 68
      },
      {
        "id": "lava_canyon-w3",
        "kind": "wild",
        "speciesId": "numel",
        "level": 29,
        "x": 74,
        "y": 44
      },
      {
        "id": "lava_canyon-w4",
        "kind": "wild",
        "speciesId": "torchic",
        "level": 30,
        "x": 88,
        "y": 58
      },
      {
        "id": "lava_canyon-t0",
        "kind": "trainer",
        "trainerName": "熔岩旅人",
        "reward": 1600,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "cyndaquil",
            "level": 27
          },
          {
            "speciesId": "growlithe",
            "level": 29
          },
          {
            "speciesId": "slugma",
            "level": 31
          },
          {
            "speciesId": "numel",
            "level": 33
          }
        ]
      },
      {
        "id": "lava_canyon-t1",
        "kind": "trainer",
        "trainerName": "炎之学者",
        "reward": 1900,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "cyndaquil",
            "level": 28
          },
          {
            "speciesId": "growlithe",
            "level": 30
          },
          {
            "speciesId": "slugma",
            "level": 32
          }
        ]
      }
    ]
  },
  "deep_trench": {
    "id": "deep_trench",
    "name": "深海海沟",
    "image": "assets/maps/deep_trench.png",
    "bossChance": 0.13999999999999999,
    "encounters": [
      {
        "id": "deep_trench-w0",
        "kind": "wild",
        "speciesId": "totodile",
        "level": 31,
        "x": 22,
        "y": 62
      },
      {
        "id": "deep_trench-w1",
        "kind": "wild",
        "speciesId": "poliwag",
        "level": 32,
        "x": 40,
        "y": 48
      },
      {
        "id": "deep_trench-w2",
        "kind": "wild",
        "speciesId": "staryu",
        "level": 33,
        "x": 58,
        "y": 68
      },
      {
        "id": "deep_trench-w3",
        "kind": "wild",
        "speciesId": "chinchou",
        "level": 34,
        "x": 74,
        "y": 44
      },
      {
        "id": "deep_trench-w4",
        "kind": "wild",
        "speciesId": "piplup",
        "level": 35,
        "x": 88,
        "y": 58
      },
      {
        "id": "deep_trench-t0",
        "kind": "trainer",
        "trainerName": "潜水员",
        "reward": 1950,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "totodile",
            "level": 32
          },
          {
            "speciesId": "poliwag",
            "level": 34
          },
          {
            "speciesId": "staryu",
            "level": 36
          },
          {
            "speciesId": "chinchou",
            "level": 38
          }
        ]
      },
      {
        "id": "deep_trench-t1",
        "kind": "trainer",
        "trainerName": "航海士",
        "reward": 2250,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "totodile",
            "level": 33
          },
          {
            "speciesId": "poliwag",
            "level": 35
          },
          {
            "speciesId": "staryu",
            "level": 37
          }
        ]
      }
    ]
  },
  "gloom_yard": {
    "id": "gloom_yard",
    "name": "幽暗墓园",
    "image": "assets/maps/gloom_yard.png",
    "bossChance": 0.16,
    "encounters": [
      {
        "id": "gloom_yard-w0",
        "kind": "wild",
        "speciesId": "misdreavus",
        "level": 36,
        "x": 22,
        "y": 62
      },
      {
        "id": "gloom_yard-w1",
        "kind": "wild",
        "speciesId": "sableye",
        "level": 37,
        "x": 40,
        "y": 48
      },
      {
        "id": "gloom_yard-w2",
        "kind": "wild",
        "speciesId": "shuppet",
        "level": 38,
        "x": 58,
        "y": 68
      },
      {
        "id": "gloom_yard-w3",
        "kind": "wild",
        "speciesId": "duskull",
        "level": 39,
        "x": 74,
        "y": 44
      },
      {
        "id": "gloom_yard-w4",
        "kind": "wild",
        "speciesId": "murkrow",
        "level": 40,
        "x": 88,
        "y": 58
      },
      {
        "id": "gloom_yard-t0",
        "kind": "trainer",
        "trainerName": "守墓人",
        "reward": 2300,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "misdreavus",
            "level": 37
          },
          {
            "speciesId": "sableye",
            "level": 39
          },
          {
            "speciesId": "shuppet",
            "level": 41
          },
          {
            "speciesId": "duskull",
            "level": 43
          }
        ]
      },
      {
        "id": "gloom_yard-t1",
        "kind": "trainer",
        "trainerName": "灵媒",
        "reward": 2600,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "misdreavus",
            "level": 38
          },
          {
            "speciesId": "sableye",
            "level": 40
          },
          {
            "speciesId": "shuppet",
            "level": 42
          }
        ]
      }
    ]
  },
  "moss_wilds": {
    "id": "moss_wilds",
    "name": "苔原密林",
    "image": "assets/maps/moss_wilds.png",
    "bossChance": 0.18,
    "encounters": [
      {
        "id": "moss_wilds-w0",
        "kind": "wild",
        "speciesId": "treecko",
        "level": 41,
        "x": 22,
        "y": 62
      },
      {
        "id": "moss_wilds-w1",
        "kind": "wild",
        "speciesId": "bellsprout",
        "level": 42,
        "x": 40,
        "y": 48
      },
      {
        "id": "moss_wilds-w2",
        "kind": "wild",
        "speciesId": "paras",
        "level": 43,
        "x": 58,
        "y": 68
      },
      {
        "id": "moss_wilds-w3",
        "kind": "wild",
        "speciesId": "scyther",
        "level": 44,
        "x": 74,
        "y": 44
      },
      {
        "id": "moss_wilds-w4",
        "kind": "wild",
        "speciesId": "snivy",
        "level": 45,
        "x": 88,
        "y": 58
      },
      {
        "id": "moss_wilds-t0",
        "kind": "trainer",
        "trainerName": "园丁",
        "reward": 2650,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "treecko",
            "level": 42
          },
          {
            "speciesId": "bellsprout",
            "level": 44
          },
          {
            "speciesId": "paras",
            "level": 46
          },
          {
            "speciesId": "scyther",
            "level": 48
          }
        ]
      },
      {
        "id": "moss_wilds-t1",
        "kind": "trainer",
        "trainerName": "昆虫学家",
        "reward": 2950,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "treecko",
            "level": 43
          },
          {
            "speciesId": "bellsprout",
            "level": 45
          },
          {
            "speciesId": "paras",
            "level": 47
          }
        ]
      }
    ]
  },
  "volt_plain": {
    "id": "volt_plain",
    "name": "雷鸣平原",
    "image": "assets/maps/volt_plain.png",
    "bossChance": 0.2,
    "encounters": [
      {
        "id": "volt_plain-w0",
        "kind": "wild",
        "speciesId": "electrike",
        "level": 46,
        "x": 22,
        "y": 62
      },
      {
        "id": "volt_plain-w1",
        "kind": "wild",
        "speciesId": "mareep",
        "level": 47,
        "x": 40,
        "y": 48
      },
      {
        "id": "volt_plain-w2",
        "kind": "wild",
        "speciesId": "voltorb",
        "level": 48,
        "x": 58,
        "y": 68
      },
      {
        "id": "volt_plain-w3",
        "kind": "wild",
        "speciesId": "electabuzz",
        "level": 49,
        "x": 74,
        "y": 44
      },
      {
        "id": "volt_plain-w4",
        "kind": "wild",
        "speciesId": "plusle",
        "level": 50,
        "x": 88,
        "y": 58
      },
      {
        "id": "volt_plain-t0",
        "kind": "trainer",
        "trainerName": "电工长",
        "reward": 3000,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "electrike",
            "level": 47
          },
          {
            "speciesId": "mareep",
            "level": 49
          },
          {
            "speciesId": "voltorb",
            "level": 51
          },
          {
            "speciesId": "electabuzz",
            "level": 53
          }
        ]
      },
      {
        "id": "volt_plain-t1",
        "kind": "trainer",
        "trainerName": "暴风骑士",
        "reward": 3300,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "electrike",
            "level": 48
          },
          {
            "speciesId": "mareep",
            "level": 50
          },
          {
            "speciesId": "voltorb",
            "level": 52
          }
        ]
      }
    ]
  },
  "frost_shrine": {
    "id": "frost_shrine",
    "name": "冰封神殿",
    "image": "assets/maps/frost_shrine.png",
    "bossChance": 0.22,
    "encounters": [
      {
        "id": "frost_shrine-w0",
        "kind": "wild",
        "speciesId": "swinub",
        "level": 51,
        "x": 22,
        "y": 62
      },
      {
        "id": "frost_shrine-w1",
        "kind": "wild",
        "speciesId": "snover",
        "level": 52,
        "x": 40,
        "y": 48
      },
      {
        "id": "frost_shrine-w2",
        "kind": "wild",
        "speciesId": "sneasel",
        "level": 53,
        "x": 58,
        "y": 68
      },
      {
        "id": "frost_shrine-w3",
        "kind": "wild",
        "speciesId": "cubchoo",
        "level": 54,
        "x": 74,
        "y": 44
      },
      {
        "id": "frost_shrine-w4",
        "kind": "wild",
        "speciesId": "vanillite",
        "level": 55,
        "x": 88,
        "y": 58
      },
      {
        "id": "frost_shrine-t0",
        "kind": "trainer",
        "trainerName": "祭司",
        "reward": 3350,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "swinub",
            "level": 52
          },
          {
            "speciesId": "snover",
            "level": 54
          },
          {
            "speciesId": "sneasel",
            "level": 56
          },
          {
            "speciesId": "cubchoo",
            "level": 58
          }
        ]
      },
      {
        "id": "frost_shrine-t1",
        "kind": "trainer",
        "trainerName": "雪原猎人",
        "reward": 3650,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "swinub",
            "level": 53
          },
          {
            "speciesId": "snover",
            "level": 55
          },
          {
            "speciesId": "sneasel",
            "level": 57
          }
        ]
      }
    ]
  },
  "bone_waste": {
    "id": "bone_waste",
    "name": "龙骨荒原",
    "image": "assets/maps/bone_waste.png",
    "bossChance": 0.24,
    "encounters": [
      {
        "id": "bone_waste-w0",
        "kind": "wild",
        "speciesId": "larvitar",
        "level": 56,
        "x": 22,
        "y": 62
      },
      {
        "id": "bone_waste-w1",
        "kind": "wild",
        "speciesId": "gible",
        "level": 57,
        "x": 40,
        "y": 48
      },
      {
        "id": "bone_waste-w2",
        "kind": "wild",
        "speciesId": "axew",
        "level": 58,
        "x": 58,
        "y": 68
      },
      {
        "id": "bone_waste-w3",
        "kind": "wild",
        "speciesId": "trapinch",
        "level": 59,
        "x": 74,
        "y": 44
      },
      {
        "id": "bone_waste-w4",
        "kind": "wild",
        "speciesId": "rhyhorn",
        "level": 60,
        "x": 88,
        "y": 58
      },
      {
        "id": "bone_waste-t0",
        "kind": "trainer",
        "trainerName": "化石猎人",
        "reward": 3700,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "larvitar",
            "level": 57
          },
          {
            "speciesId": "gible",
            "level": 59
          },
          {
            "speciesId": "axew",
            "level": 61
          },
          {
            "speciesId": "trapinch",
            "level": 63
          }
        ]
      },
      {
        "id": "bone_waste-t1",
        "kind": "trainer",
        "trainerName": "龙之使者",
        "reward": 4000,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "larvitar",
            "level": 58
          },
          {
            "speciesId": "gible",
            "level": 60
          },
          {
            "speciesId": "axew",
            "level": 62
          }
        ]
      }
    ]
  },
  "fairy_court": {
    "id": "fairy_court",
    "name": "妖精庭园",
    "image": "assets/maps/fairy_court.png",
    "bossChance": 0.26,
    "encounters": [
      {
        "id": "fairy_court-w0",
        "kind": "wild",
        "speciesId": "clefairy",
        "level": 61,
        "x": 22,
        "y": 62
      },
      {
        "id": "fairy_court-w1",
        "kind": "wild",
        "speciesId": "jigglypuff",
        "level": 62,
        "x": 40,
        "y": 48
      },
      {
        "id": "fairy_court-w2",
        "kind": "wild",
        "speciesId": "togepi",
        "level": 63,
        "x": 58,
        "y": 68
      },
      {
        "id": "fairy_court-w3",
        "kind": "wild",
        "speciesId": "snubbull",
        "level": 64,
        "x": 74,
        "y": 44
      },
      {
        "id": "fairy_court-w4",
        "kind": "wild",
        "speciesId": "marill",
        "level": 65,
        "x": 88,
        "y": 58
      },
      {
        "id": "fairy_court-t0",
        "kind": "trainer",
        "trainerName": "庭园侍女",
        "reward": 4050,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "clefairy",
            "level": 62
          },
          {
            "speciesId": "jigglypuff",
            "level": 64
          },
          {
            "speciesId": "togepi",
            "level": 66
          },
          {
            "speciesId": "snubbull",
            "level": 68
          }
        ]
      },
      {
        "id": "fairy_court-t1",
        "kind": "trainer",
        "trainerName": "诗人",
        "reward": 4350,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "clefairy",
            "level": 63
          },
          {
            "speciesId": "jigglypuff",
            "level": 65
          },
          {
            "speciesId": "togepi",
            "level": 67
          }
        ]
      }
    ]
  },
  "fight_dojo": {
    "id": "fight_dojo",
    "name": "格斗道场",
    "image": "assets/maps/fight_dojo.png",
    "bossChance": 0.28,
    "encounters": [
      {
        "id": "fight_dojo-w0",
        "kind": "wild",
        "speciesId": "hitmonlee",
        "level": 66,
        "x": 22,
        "y": 62
      },
      {
        "id": "fight_dojo-w1",
        "kind": "wild",
        "speciesId": "hitmonchan",
        "level": 67,
        "x": 40,
        "y": 48
      },
      {
        "id": "fight_dojo-w2",
        "kind": "wild",
        "speciesId": "tyrogue",
        "level": 68,
        "x": 58,
        "y": 68
      },
      {
        "id": "fight_dojo-w3",
        "kind": "wild",
        "speciesId": "makuhita",
        "level": 69,
        "x": 74,
        "y": 44
      },
      {
        "id": "fight_dojo-w4",
        "kind": "wild",
        "speciesId": "riolu",
        "level": 70,
        "x": 88,
        "y": 58
      },
      {
        "id": "fight_dojo-t0",
        "kind": "trainer",
        "trainerName": "馆主弟子",
        "reward": 4400,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "hitmonlee",
            "level": 67
          },
          {
            "speciesId": "hitmonchan",
            "level": 69
          },
          {
            "speciesId": "tyrogue",
            "level": 71
          },
          {
            "speciesId": "makuhita",
            "level": 73
          }
        ]
      },
      {
        "id": "fight_dojo-t1",
        "kind": "trainer",
        "trainerName": "空手道家",
        "reward": 4700,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "hitmonlee",
            "level": 68
          },
          {
            "speciesId": "hitmonchan",
            "level": 70
          },
          {
            "speciesId": "tyrogue",
            "level": 72
          }
        ]
      }
    ]
  },
  "final_realm": {
    "id": "final_realm",
    "name": "终焉领域",
    "image": "assets/maps/final_realm.png",
    "bossChance": 0.3,
    "encounters": [
      {
        "id": "final_realm-w0",
        "kind": "wild",
        "speciesId": "lucario",
        "level": 71,
        "x": 22,
        "y": 62
      },
      {
        "id": "final_realm-w1",
        "kind": "wild",
        "speciesId": "garchomp",
        "level": 72,
        "x": 40,
        "y": 48
      },
      {
        "id": "final_realm-w2",
        "kind": "wild",
        "speciesId": "metagross",
        "level": 73,
        "x": 58,
        "y": 68
      },
      {
        "id": "final_realm-w3",
        "kind": "wild",
        "speciesId": "tyranitar",
        "level": 74,
        "x": 74,
        "y": 44
      },
      {
        "id": "final_realm-w4",
        "kind": "wild",
        "speciesId": "togekiss",
        "level": 75,
        "x": 88,
        "y": 58
      },
      {
        "id": "final_realm-t0",
        "kind": "trainer",
        "trainerName": "领域守卫",
        "reward": 4750,
        "x": 30,
        "y": 30,
        "team": [
          {
            "speciesId": "lucario",
            "level": 72
          },
          {
            "speciesId": "garchomp",
            "level": 74
          },
          {
            "speciesId": "metagross",
            "level": 76
          },
          {
            "speciesId": "tyranitar",
            "level": 78
          }
        ]
      },
      {
        "id": "final_realm-t1",
        "kind": "trainer",
        "trainerName": "终焉冠军",
        "reward": 5050,
        "x": 66,
        "y": 26,
        "team": [
          {
            "speciesId": "lucario",
            "level": 73
          },
          {
            "speciesId": "garchomp",
            "level": 75
          },
          {
            "speciesId": "metagross",
            "level": 77
          }
        ]
      }
    ]
  }
};
